### PR TITLE
Fix for linux compile.

### PR DESCRIPTION
**Pull request by Aikonlee**
VS 2013.update 4
OpenSSL 1.0.0q/1.0.2a (32bit)
ACE 6.1.4
build passing

Debian 7.8 amd64
OpenSSL 1.0.1e
ACE 6.0.3
build passing

Sorry:
Now,
zone_echo_isles.cpp is blocked.
It need to be continue fix.
Here:
src/server/game/Scripting/ScriptLoader.cpp
src/server/scripts/Kalimdor/zone_echo_isles.cpp

### CODE REVIEW

**Comment by Exodius** [comment]
I gotta ask. Did you copy/paste some other repository in it's entirety over the NG and then commit the changes? Couldn't you  have updated the things 1 by 1 so it can be seen what was changed?

**Comment by Jiinx** [comment]
commenting out "the problem" is not a proper solution..

Issue resolved in https://github.com/Arkania/ArkCORE-NG/commit/9fd334c4ab7ec2aedfb5e16be3a657c9c7c26251

**Comment by gpn39f** [comment]
you wrote: commenting out "the problem" is not a proper solution..

where have I comment this out? I was add a additional function with accept the unit\* as var and not as pointer. the first entry in this report, show my work..

**Comment by Jiinx** [comment]
The comment was directed to the OP (aikonlee). His pull request, on top of being a full repo only commented out lines in zone_echo_isles.cpp.

This was the same issue that I provided to you which is now resolved as of https://github.com/Arkania/ArkCORE-NG/commit/9fd334c4ab7ec2aedfb5e16be3a657c9c7c26251

**Comment by gpn39f** [comment]
ok.. thanks.. 
I can't read the big pull request he made.. 229 files changed.. my explorer give up after 10 minutes of waiting to the git site..

**Comment by Jiinx** [comment]
this can be closed

**Pull request closed without merging**
