### PR TITLE
fix quest 25409 (forces of nature: Hyppogryphs)

### PR DESCRIPTION
**Pull request by Snuffleclaws**

### CODE REVIEW

**Comment by gpn39f** [comment]
on first look : super.. it is nice to see you can help me.. let me import it local before i import it global.. i have to read more how to do.. u are the first deliver pushed fixes :-)

**Comment by Snuffleclaws** [comment]
I found out that creature->AddToWorld() is not necessary when using DoSpawnCreature, it should be removed. Also _poacher_check variable is unused, i forgot to remove it.

I also have the next one completed (treants).

**Comment by gpn39f** [comment]
u are using the wrong npc counter.. 5300 and 5304 are wrong..
if i look into the quest_template i see the npc counter are 40072 and 40090

**Comment by Snuffleclaws** [comment]
I looked up 40072 and the npc is a small bunny and 40090 is also a bunny but for next quest (Treants). It looks like it is used to track quest progress. So if you look at the script code, i use 40072 to track quest progress and for the next quest, i use 40090 to track the treants recalled.
`                        
                        if (_hippo_called == true)
                        {
                            Position front_pos = me->GetNearPositionInFront(18, 0.1f);

                            me->GetMotionMaster()->Clear(true);
                            me->GetMotionMaster()->MoveJump(Position(front_pos.GetPositionX(), front_pos.GetPositionY(), me->GetPositionZ() + 18), 6.0f, 6.0f);
                            me->DespawnOrUnsummon(3000);

                            player->KilledMonsterCredit(40072);
                            _hippo_called = false;

                            _events.ScheduleEvent(EVENT_CHECK_FOR_PLAYER, 1000);
                        }
`

**Comment by Snuffleclaws** [comment]
I think i know what you mean now, i should have use _40072 for the script class name. Can you cancel the pull request, i will rename them properly and resend.

**Comment by gpn39f** [comment]
i'm nearly finish this quest.. maybe then you can see what i'm searching for, before i start writing a fix..
then i can look at video and see how the single spell and npc are working together..

**Comment by Snuffleclaws** [comment]
Another pull request is sent for 2 forces of nature quests, i think it's ok now, let me know if you find something wrong.

**Pull request closed without merging**
